#Name of workflow
name: Deploy LangChattoApp

#Branch that will trigger the workflow
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "APP_HOST=${{ secrets.APP_HOST }}" >> .env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
          echo "APP_PORT_SOCKET=${{ secrets.APP_PORT_SOCKET }}" >> .env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "ELASTIC_APM_SERVER_URL=${{ secrets.ELASTIC_APM_SERVER_URL }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build . -t ardidafa/langchatto-app
      - name: Push docker image to docker hub
        run: docker push ardidafa/langchatto-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull ardidafa/langchatto-app:latest
      - name: Delete old docker container
        run: docker rm -f langchatto-app
      - name: Running new docker container
        run: |
          docker run -d \
            -p 8080:8080 \
            -p 4000:4000 \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e APP_NAME="${{ secrets.APP_NAME }}" \
            -e APP_HOST="${{ secrets.APP_HOST }}" \
            -e APP_PORT="${{ secrets.APP_PORT }}" \
            -e APP_PORT_SOCKET="${{ secrets.APP_PORT_SOCKET }}" \
            -e APP_SECRET="${{ secrets.APP_SECRET }}" \
            -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            -e ELASTIC_APM_SERVER_URL="${{ secrets.ELASTIC_APM_SERVER_URL }}" \
            --name langchatto-app \
            ardidafa/langchatto-app